
static const char humbert_21_B2[] = "(r-1)^6*(r+1)^4*(s-r)^6";

static const char humbert_21_A[] = "-(s-r)^2*(s^2+(24*r^3+30*r^2-26*r-30)*s-15*r^4-30*r^3+7*r^2+30*r+9)/3";

static const char humbert_21_B1[] = "(r^4-2*s*r^3+(s^2-5/3)*r^2+10/3*s*r+(-2/3*s^2+2*s+1))";

static const char humbert_21_A1[] = "-1";

static const char humbert_21_B[] = "2*(s-r)^4*(s^2+(-72*r^3-63*r^2+70*r+63)*s-27*r^6-189*r^5-63*r^4+441*r^3+280*r^2-252*r-189)/27";
