
static const char humbert_24_B2[] = "(a/2)";

static const char humbert_24_A[] = "(3*a*d^2+10*a*d+(-3*a^2+5*a-1/3))";

static const char humbert_24_B1[] = "(2*a^2/3)*(-3*d^6+6*d^5+(6*a+2)*d^4-(6*a+10)*d^3-(9*a^2+5*a-3)*d^2+(6*a^2+4*a+4)*d+(3*a^3+3*a^2+a-2))";

static const char humbert_24_A1[] = "2*a^2*(d-1)^2*(d^2-a-1)";

static const char humbert_24_B[] = "((-11*a^2+3*a)*d^2+(-14*a^2+14/3*a)*d+(-5*a^2+7/3*a+2/27))";
