
static const char humbert_29_B2[] = "-1/2";

static const char humbert_29_A[] = "-(9*g^2+72*f*g-54*g+16*f^2-8*f+1)/3";

static const char humbert_29_B1[] = "-2*g^2*(3*g^4-36*f*g^3+48*f^4*g^2-16*f^3*g^2+148*f^2*g^2-64*f^4*g-224*f^3*g+512*f^5+64*f^4)/3";

static const char humbert_29_A1[] = "8*f^2*g^2*(g-4*f)^2";

static const char humbert_29_B[] = "-2*(108*f^2*g^2-162*f*g^2+405*g^2-648*f^2*g+648*f*g-135*g+64*f^3-48*f^2+12*f-1)/27";
