
static const char cardona_a111[] = "4/675*A^2*C - 8/225*B*C + 4/75*D";

static const char cardona_a112[] = "4/675*B^3 + 8/675*A*B*C + 8/225*C^2 + 2/225*A*D";

static const char cardona_a122[] = "2/675*A*B^3 + 8/2025*A^2*B*C + 8/675*B^2*C + 4/225*A*C^2 + 2/225*B*D";

static const char cardona_a133[] = "-1/2025*A^2*B^4 - 4/6075*A^3*B^2*C + 8/2025*B^5 + 14/2025*A*B^3*C + 2/2025*A^2*B*C^2 + 8/675*B^2*C^2 + 4/675*A*C^3 + 1/225*A*B^2*D + 2/675*A^2*C*D + 2/225*B*C*D - 2/75*D^2";

static const char cardona_a222[] = "2/225*B^4 + 4/225*A*B^2*C + 16/2025*A^2*C^2 + 4/675*B*C^2 - 2/225*C*D";

static const char cardona_a233[] = "1/2025*A*B^5 + 2/1215*A^2*B^3*C + 8/6075*A^3*B*C^2 - 2/2025*B^4*C + 2/2025*A*B^2*C^2 + 8/2025*A^2*C^3 - 4/675*B*C^3 + 2/675*B^3*D + 1/675*A*B*C*D - 2/225*C^2*D - 1/225*A*D^2";

static const char cardona_A11[] = "1/3*A*B + 2*C";

static const char cardona_A12[] = "2/3*B^2 + 2/3*A*C";

static const char cardona_A22[] = "D";

static const char cardona_A33[] = "-2/9*B^4 - 4/9*A*B^2*C - 2/9*A^2*C^2 + 1/6*A*B*D + C*D";

