
static const char hilbert_17_h[] = "(2*g + 1)*4/27 + m/27*(2*g+1)*(27*g+13)";

static const char hilbert_17_gnum[] = "-(3*n^2+36*m*n+198*n+13312*m^3-7584*m^2-11364*m+55)";

static const char hilbert_17_gden[] = "3*(2*(n^2+4608*m^3-1728*m^2+216*m-9))";

static const char hilbert_8_snum[] = "m*(16*r-1)-((32*r)*(r -5/4) - 1)";

static const char hilbert_8_rnum[] = "(m^2-1)";

static const char hilbert_8_sden[] = "32*r";

static const char hilbert_8_rden[] = "(16*(2*n^2-1)) ";

static const char hilbert_12_eden[] = "(g^2-27*f^2+27)";

static const char hilbert_12_enum[] = "-2*(f-1)*(f+1)*(f^2*g+9*f^2-8)";

static const char hilbert_13_g2den[] = "(n^2-12*m^3+3*m^2)";

static const char hilbert_13_g2num[] = "(n^2-72*m*n-1440*n+1803*m^2+3168*m-768)";

static const char hilbert_5_g[] = "-(5*n^2-m^2+9)/30";

static const char hilbert_5_h[] = "3*m*(10*g+3)*(15*g+2)/6250  + 9*(250*g^2+75*g+6)/6250";
