
static const char mestre_cubic_c122[] = "4*(A*B^3+4*A^2*B*C/3+4*B^2*C+6*A*C^2+3*B*D)/36";

static const char mestre_cubic_c113[] = "4*(A*B^3+4*A^2*B*C/3+4*B^2*C+6*A*C^2+3*B*D)/36";

static const char mestre_cubic_c112[] = "4*(2*B^3+4*A*B*C+12*C^2+3*A*D)/36";

static const char mestre_cubic_c123[] = "2*(2*B^4+4*A*B^2*C+4*A^2*C^2/3+4*B*C^2+3*A*B*D+12*C*D)/36";

static const char mestre_cubic_c222[] = "4*(3*B^4+6*A*B^2*C+8*A^2*C^2/3+2*B*C^2-3*C*D)/36";

static const char mestre_cubic_c223[] = "2*(-2*B^3*C/3-4*A*B*C^2/3-4*C^3+9*B^2*D+8*A*C*D)/36";

static const char mestre_cubic_c333[] = "1*(-2*B^4*C-4*A*B^2*C^2-16*A^2*C^3/9-4*B*C^3/3 +9*B^3*D+12*A*B*C*D+20*C^2*D)/36";

static const char mestre_cubic_c111[] = "8*(A^2*C-6*B*C+9*D)/36";

static const char mestre_cubic_c233[] = "2*(B^5+2*A*B^3*C+8*A^2*B*C^2/9+2*B^2*C^2/3 -B*C*D+9*D^2)/36";

static const char mestre_cubic_c133[] = "2*(A*B^4+4*A^2*B^2*C/3+16*B^3*C/3+26*A*B*C^2/3+ 8*C^3+3*B^2*D+2*A*C*D)/36";

static const char mestre_conic_A33[] = "B*D/2+2*C*(B^2+A*C)/9";

static const char mestre_conic_A11[] = "2*C+A*B/3";

static const char mestre_conic_A31[] = "D";

static const char mestre_conic_A22[] = "D";

static const char mestre_conic_A12[] = "2*(B^2+A*C)/3";

static const char mestre_conic_A23[] = "B*(B^2+A*C)/3+C*(2*C+A*B/3)/3";
